# This workflow will perform a patch increment on the version field of the package.json, package-lock.json, and lib/lcp_manifest.json.
# It then pushes the version change with an accompanying git tag using the Add & Commit action. Documentation here: https://github.com/marketplace/actions/add-commit

name: Bump Version & Tag

on:
  workflow_call:

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm version patch --git-tag-version=false
      - run: echo VERSION=$(jq -j '.version' ./package.json) >> $GITHUB_ENV
      - name: Update LCP Manifest
        run: |
          if [[ -w ./lib/lcp_manifest.json ]]; then
            tmp=$(mktemp)
            jq --arg version "${{ env.VERSION }}" '.version = $version' ./lib/lcp_manifest.json > "$tmp" && mv "$tmp" ./lib/lcp_manifest.json
          fi

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: "bump to ${{ env.VERSION }}"
          tag: ${{ env.VERSION }} -a -m "Release version ${{ env.VERSION }}"